[project]
name = "claude-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docker>=7.1.0",
    "fastmcp>=2.11.3",
    "httpx>=0.28.1",
    "jsonpatch>=1.33",
    "uvicorn>=0.35.0",
]
