name: Docker Build ARM64

on:
  push:
    branches: [ main ]
    paths: [ 'src/docker/**' ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: cheolwanpark/claude-agent

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch,suffix=-arm64
          type=ref,event=tag,suffix=-arm64
          type=raw,value=latest-arm64,enable={{is_default_branch}}

    - name: Build and push ARM64 image
      uses: docker/build-push-action@v5
      with:
        context: ./src/docker
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=arm64
        cache-to: type=gha,mode=max,scope=arm64